/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.s097t0r1.telegram.notifier

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'org.s097t0r1.telegram.notifier.greeting' plugin.
 */
class TelegramNotifierPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('org.s097t0r1.telegram-notifier') version "0.1"
            }
            
            telegramNotifier {
                token = "1511019343:AAFMY2zihHo8dmTzDz_eVQiRxDE0fanPDRo"
                chatId = 139228903
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("telegramNotifier")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Message was sent"))
    }
}
