/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.s097t0r1.telegram.notifier

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * Telegram notifier plugin class.
 */
class TelegramNotifierPlugin: Plugin<Project> {
    override fun apply(project: Project) {

        val extension = project.extensions.create("telegramNotifier", TelegramNotifierPluginExtension::class.java)

        // Register a task
        project.tasks.register("telegramNotifier", TelegramNotifierPluginTask::class.java) {
            it.token = extension.token
            it.chatId = extension.chatId
        }

    }
}
