/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.s097t0r1.telegram.notifier

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'org.s097t0r1.telegram.notifier.greeting' plugin.
 */
class TelegramNotifierPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply(TelegramNotifierPlugin::class.java)

        // Verify the result
        assertNotNull(project.tasks.findByName("telegramNotifier"))
    }
}
